version: '3.9'

services:
  app:
    image: laravel
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0.30
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    links:
     - mysql
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - mynetwork

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - mynetwork

networks:
  mynetwork:
