version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    image: laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: root
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - mynetwork
    
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay

volumes:
  app_data:
  mysql_data:
  nginx_conf:
